# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93ec01c2bd1d5e2dc64085afad6190d9b9634df3b2bea143dedb0008238c6d0d118b1c62d9850034a02a889e40c7da87bbe5b2f8042e630f12b763b26b91b1e

test:
  secret_key_base: e4fb569384298c2a433ce0b81dddf9a49c6a6b46b7283b53c43f00927b56b5c708c2ab2f0704dac69ff1ce5d78b47c35bd4e0866aba44c3dc391521fdd39d1eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
